//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenusIDE.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GenusIDE.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOE (*.moe)|*.moe|Okashi (*oks)|*.oks|C/C++ (*.c, *.cpp, *.cxx, *.h, *.hxx)|*.c;*.cpp;*.cxx;*.h;*.hxx|C# (*.cs)|*.cs|Java (*.java)|*.java|PHP (*.php)|*.php|HTML (*.html, *.htm)|*.html;*.htm|Text (*.txt)|*.txt|All Files|*.*.
        /// </summary>
        internal static string File_Types {
            get {
                return ResourceManager.GetString("File_Types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GenueIDE_Okashi1 {
            get {
                object obj = ResourceManager.GetObject("GenueIDE_Okashi1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon GenusIDE_C {
            get {
                object obj = ResourceManager.GetObject("GenusIDE_C", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GenusIDE_C_16x16 {
            get {
                object obj = ResourceManager.GetObject("GenusIDE_C_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GenusIDE_C1 {
            get {
                object obj = ResourceManager.GetObject("GenusIDE_C1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon GenusIDE_Compile {
            get {
                object obj = ResourceManager.GetObject("GenusIDE_Compile", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GenusIDE_Compile_16x16 {
            get {
                object obj = ResourceManager.GetObject("GenusIDE_Compile_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GenusIDE_Compile1 {
            get {
                object obj = ResourceManager.GetObject("GenusIDE_Compile1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon GenusIDE_CompileAndRun {
            get {
                object obj = ResourceManager.GetObject("GenusIDE_CompileAndRun", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GenusIDE_CompileAndRun_16x16 {
            get {
                object obj = ResourceManager.GetObject("GenusIDE_CompileAndRun_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GenusIDE_CompileAndRun1 {
            get {
                object obj = ResourceManager.GetObject("GenusIDE_CompileAndRun1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon GenusIDE_CPP {
            get {
                object obj = ResourceManager.GetObject("GenusIDE_CPP", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GenusIDE_CPP_16x16 {
            get {
                object obj = ResourceManager.GetObject("GenusIDE_CPP_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GenusIDE_CPP1 {
            get {
                object obj = ResourceManager.GetObject("GenusIDE_CPP1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon GenusIDE_CSharp {
            get {
                object obj = ResourceManager.GetObject("GenusIDE_CSharp", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GenusIDE_CSharp_16x16 {
            get {
                object obj = ResourceManager.GetObject("GenusIDE_CSharp_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GenusIDE_CSharp1 {
            get {
                object obj = ResourceManager.GetObject("GenusIDE_CSharp1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon GenusIDE_EmptyFile {
            get {
                object obj = ResourceManager.GetObject("GenusIDE_EmptyFile", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GenusIDE_EmptyFile_16x16 {
            get {
                object obj = ResourceManager.GetObject("GenusIDE_EmptyFile_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GenusIDE_EmptyFile1 {
            get {
                object obj = ResourceManager.GetObject("GenusIDE_EmptyFile1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon GenusIDE_Find {
            get {
                object obj = ResourceManager.GetObject("GenusIDE_Find", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GenusIDE_Find_16x16 {
            get {
                object obj = ResourceManager.GetObject("GenusIDE_Find_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GenusIDE_Find1 {
            get {
                object obj = ResourceManager.GetObject("GenusIDE_Find1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon GenusIDE_Help {
            get {
                object obj = ResourceManager.GetObject("GenusIDE_Help", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GenusIDE_Help_16x16 {
            get {
                object obj = ResourceManager.GetObject("GenusIDE_Help_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GenusIDE_Help1 {
            get {
                object obj = ResourceManager.GetObject("GenusIDE_Help1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GenusIDE_HelpForm {
            get {
                object obj = ResourceManager.GetObject("GenusIDE_HelpForm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon GenusIDE_Hotkeys {
            get {
                object obj = ResourceManager.GetObject("GenusIDE_Hotkeys", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GenusIDE_Hotkeys_16x16 {
            get {
                object obj = ResourceManager.GetObject("GenusIDE_Hotkeys_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GenusIDE_Hotkeys1 {
            get {
                object obj = ResourceManager.GetObject("GenusIDE_Hotkeys1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon GenusIDE_HTML {
            get {
                object obj = ResourceManager.GetObject("GenusIDE_HTML", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GenusIDE_HTML_16x16 {
            get {
                object obj = ResourceManager.GetObject("GenusIDE_HTML_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GenusIDE_HTML1 {
            get {
                object obj = ResourceManager.GetObject("GenusIDE_HTML1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon GenusIDE_Java {
            get {
                object obj = ResourceManager.GetObject("GenusIDE_Java", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GenusIDE_Java_16x16 {
            get {
                object obj = ResourceManager.GetObject("GenusIDE_Java_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GenusIDE_Java1 {
            get {
                object obj = ResourceManager.GetObject("GenusIDE_Java1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GenusIDE_LineNumbers {
            get {
                object obj = ResourceManager.GetObject("GenusIDE_LineNumbers", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon GenusIDE_Main {
            get {
                object obj = ResourceManager.GetObject("GenusIDE_Main", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GenusIDE_Main_16x16 {
            get {
                object obj = ResourceManager.GetObject("GenusIDE_Main_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GenusIDE_Main1 {
            get {
                object obj = ResourceManager.GetObject("GenusIDE_Main1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon GenusIDE_MOE {
            get {
                object obj = ResourceManager.GetObject("GenusIDE_MOE", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GenusIDE_MOE_16x16 {
            get {
                object obj = ResourceManager.GetObject("GenusIDE_MOE_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GenusIDE_MOE1 {
            get {
                object obj = ResourceManager.GetObject("GenusIDE_MOE1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon GenusIDE_New {
            get {
                object obj = ResourceManager.GetObject("GenusIDE_New", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GenusIDE_New_16x16 {
            get {
                object obj = ResourceManager.GetObject("GenusIDE_New_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GenusIDE_New1 {
            get {
                object obj = ResourceManager.GetObject("GenusIDE_New1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon GenusIDE_Okashi {
            get {
                object obj = ResourceManager.GetObject("GenusIDE_Okashi", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GenusIDE_Okashi_16x16 {
            get {
                object obj = ResourceManager.GetObject("GenusIDE_Okashi_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon GenusIDE_Open {
            get {
                object obj = ResourceManager.GetObject("GenusIDE_Open", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GenusIDE_Open_16x16 {
            get {
                object obj = ResourceManager.GetObject("GenusIDE_Open_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GenusIDE_Open1 {
            get {
                object obj = ResourceManager.GetObject("GenusIDE_Open1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon GenusIDE_Pause {
            get {
                object obj = ResourceManager.GetObject("GenusIDE_Pause", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GenusIDE_Pause_16x16 {
            get {
                object obj = ResourceManager.GetObject("GenusIDE_Pause_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GenusIDE_Pause1 {
            get {
                object obj = ResourceManager.GetObject("GenusIDE_Pause1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon GenusIDE_PHP {
            get {
                object obj = ResourceManager.GetObject("GenusIDE_PHP", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GenusIDE_PHP_16x16 {
            get {
                object obj = ResourceManager.GetObject("GenusIDE_PHP_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GenusIDE_PHP1 {
            get {
                object obj = ResourceManager.GetObject("GenusIDE_PHP1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon GenusIDE_Print {
            get {
                object obj = ResourceManager.GetObject("GenusIDE_Print", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GenusIDE_Print_16x16 {
            get {
                object obj = ResourceManager.GetObject("GenusIDE_Print_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GenusIDE_Print1 {
            get {
                object obj = ResourceManager.GetObject("GenusIDE_Print1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GenusIDE_Redo {
            get {
                object obj = ResourceManager.GetObject("GenusIDE_Redo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon GenusIDE_Run {
            get {
                object obj = ResourceManager.GetObject("GenusIDE_Run", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GenusIDE_Run_16x16 {
            get {
                object obj = ResourceManager.GetObject("GenusIDE_Run_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GenusIDE_Run1 {
            get {
                object obj = ResourceManager.GetObject("GenusIDE_Run1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon GenusIDE_Save {
            get {
                object obj = ResourceManager.GetObject("GenusIDE_Save", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GenusIDE_Save_16x16 {
            get {
                object obj = ResourceManager.GetObject("GenusIDE_Save_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GenusIDE_Save1 {
            get {
                object obj = ResourceManager.GetObject("GenusIDE_Save1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon GenusIDE_SaveAs {
            get {
                object obj = ResourceManager.GetObject("GenusIDE_SaveAs", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GenusIDE_SaveAs_16x16 {
            get {
                object obj = ResourceManager.GetObject("GenusIDE_SaveAs_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GenusIDE_SaveAs1 {
            get {
                object obj = ResourceManager.GetObject("GenusIDE_SaveAs1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon GenusIDE_Settings {
            get {
                object obj = ResourceManager.GetObject("GenusIDE_Settings", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GenusIDE_Settings_16x16 {
            get {
                object obj = ResourceManager.GetObject("GenusIDE_Settings_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GenusIDE_Settings1 {
            get {
                object obj = ResourceManager.GetObject("GenusIDE_Settings1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GenusIDE_ShowEOL {
            get {
                object obj = ResourceManager.GetObject("GenusIDE_ShowEOL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GenusIDE_Splash {
            get {
                object obj = ResourceManager.GetObject("GenusIDE_Splash", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon GenusIDE_Stop {
            get {
                object obj = ResourceManager.GetObject("GenusIDE_Stop", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GenusIDE_Stop_16x16 {
            get {
                object obj = ResourceManager.GetObject("GenusIDE_Stop_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GenusIDE_Stop1 {
            get {
                object obj = ResourceManager.GetObject("GenusIDE_Stop1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GenusIDE_Undo {
            get {
                object obj = ResourceManager.GetObject("GenusIDE_Undo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GenusIDE_Whitespace {
            get {
                object obj = ResourceManager.GetObject("GenusIDE_Whitespace", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GenusIDE_WordWrap {
            get {
                object obj = ResourceManager.GetObject("GenusIDE_WordWrap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GenusIDE_Zoom {
            get {
                object obj = ResourceManager.GetObject("GenusIDE_Zoom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ScintillaNET&gt;
        ///  &lt;Language Name=&quot;java&quot;&gt;
        ///    &lt;AutoComplete FillUpCharacters=&quot;.([&quot; SingleLineAccept=&quot;True&quot; IsCaseSensitive=&quot;False&quot;&gt;
        ///      &lt;List&gt;
        ///        abstract assert boolean break byte case catch char class continue default do double else enum extends 
        ///        final finally float for if import int interface long native new package private protected public return
        ///        short static strictfp super switch synchronized this throw throws transient try void volatil [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string java {
            get {
                return ResourceManager.GetString("java", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ScintillaNET&gt;
        ///	&lt;Language Name=&quot;moe&quot;&gt;
        ///		&lt;AutoComplete FillUpCharacters=&quot;.([&quot; SingleLineAccept=&quot;True&quot; IsCaseSensitive=&quot;False&quot;&gt;
        ///			&lt;List&gt;
        ///				add arry as bool cnst dqe eqe flse flt inpt is itr lst no num pop prnt push rpt rtrn str true
        ///			&lt;/List&gt;
        ///		&lt;/AutoComplete&gt;
        ///
        ///		&lt;Indentation TabWidth=&quot;4&quot; SmartIndentType=&quot;cpp&quot; /&gt;
        ///			
        ///		
        ///		&lt;Lexer LineCommentPrefix=&quot;//&quot;&gt;
        ///			&lt;Keywords List=&quot;0&quot; Inherit=&quot;False&quot;&gt;
        ///				add as cnst dqe eqe flse inpt is itr lst no pop prnt push r [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string moe {
            get {
                return ResourceManager.GetString("moe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;ScintillaNET&gt;
        ///	&lt;Language Name=&quot;default&quot;&gt;
        ///		&lt;Styles&gt;
        ///			&lt;Style Name=&quot;Default&quot; FontName=&quot;Consolas&quot;/&gt;
        ///		&lt;/Styles&gt;
        ///	&lt;/Language&gt;
        ///&lt;/ScintillaNET&gt;.
        /// </summary>
        internal static string ScintillaNET {
            get {
                return ResourceManager.GetString("ScintillaNET", resourceCulture);
            }
        }
    }
}
